# Simple module to read JSON data generated by WebPlotDigitizer
# 
# Note: This is in a very initial stage right now! Use with caution!
import json
import numpy as np

class JSONData:
    def __init__(self, filename):
        with open(filename) as data_file:
            self.data = json.load(data_file)

    def getDatasetCount(self):
        return len(self.data['wpd']['dataSeries'])

    def getDatasetByIndex(self, index):
        return self.data['wpd']['dataSeries'][index]

    def getDatasetByName(self, name):
        return [x for x in self.data['wpd']['dataSeries'] if x['name'] == name][0]

    def getDatasetNames(self):
        return [x['name'] for x in self.data['wpd']['dataSeries']]

    def getDatasetValues(self, dataset):
        values = []
        for val in dataset['data']:
            values.append(val['value'])
        return np.array(values)

